name: Atualizar Tesouro Direto

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-tesouro-direto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Run Script
        run: node downloadTesouro.js
